### ISSUE TITLE
Predict arx plot changes confidence interval each time it is run

### ISSUE THREAD

**Issue by moritzpschwarz** [gsucarrat/gets#25]
When I run the following code, I get different plots when I repeat the command: 

```
library(gets)
set.seed(123)
vY <- rnorm(20)
mymodel <- arx(vY, mc=TRUE, ar=1)
options(plot=TRUE)

predict(mymodel)

predict(mymodel)

predict(mymodel)
```

In my understanding, all plots would need to be exactly the same, because the model of the `predict` function does not change. But each time I run it, the light grey confidence interval changes a bit - is there a random element in there?
Is this just on my machine? 
Is this intended? 

Below three examples of the same command, each time CI slightly different.

![image](https://user-images.githubusercontent.com/30114680/98591055-ff326700-22cf-11eb-91f8-a602c389daa1.png)
![image](https://user-images.githubusercontent.com/30114680/98591064-02c5ee00-22d0-11eb-8872-704a21a95eb7.png)
![image](https://user-images.githubusercontent.com/30114680/98591099-0c4f5600-22d0-11eb-9759-b09202924c0b.png)

**Comment by gsucarrat** [comment]
The confidence intervals are indeed generated by means of (parametric Bootstrap) simulation. This is partially described in the help file: help(predict.arx). This is also noted in our JSS article. The reason is that the prediction formulas would be excessively complex if they were to handle the AR-X and log-ARCH-X specifications. Also, the simulation method allows for non-normal (standardised) errors.

For reproducibility, you should set the seed, say, set.seed(123). Another possibility is to increase the number of simulations (the default is 5000) via the n.sim argument. If n.sim is large enough, there should not be much difference between each run.
