### ISSUE TITLE
How to add lagged y as a regressor using logitx?

### ISSUE THREAD

**Issue by nkretzmann** [gsucarrat/gets#69]
Using: model <- logitx(y, ar = 1, xreg = x) returns a model with an intercept, ar1, and the predictors from the x matrix.  
Couldn't find a way to add lag(y, 1) as a regressor - when I try to do it including a lagged y in the x matrix, there's a singularity error and it gets dropped.

**Comment by jforest443** [comment]
First lag of y is what AR1 is. Adding it twice causes the error. You therefore include 2 identical regressors. 

Sent from Yahoo Mail on Android 
 
  On Sat, Apr 8, 2023 at 1:57 PM, ***@***.***> wrote:   


Using: model <- logitx(y, ar = 1, xreg = x) returns a model with an intercept, ar1, and the predictors from the x matrix.
Couldn't find a way to add lag(y, 1) as a regressor - when I try to do it including a lagged y in the x matrix, there's a singularity error and it gets dropped.

**Comment by nkretzmann** [comment]
Thanks for the fast reply. Then this means I'm estimating the dynamic logit (equivalent to equation (9) in the original Kauppi and Saikkonen paper), right?
How should I write the logitx function in order to also estimate only the autoregressive specification and also the dynamic autoregressive specification?

**Comment by jforest443** [comment]
If you only want the dynamic form without regressors just leave out the x variables. 

Sent from Yahoo Mail on Android 
 
  On Sat, Apr 8, 2023 at 3:08 PM, ***@***.***> wrote:   


Thanks for the fast reply. Then this means I'm estimating the dynamic logit (equivalent to equation (9) in the original Kauppi and Saikkonen paper), right?
How should I write the logitx function in order to also estimate only the autoregressive specification and also the dynamic autoregressive specification?

**Comment by nkretzmann** [comment]
But I want to keep the regressors. Just like in the original paper, I would like to estimate the 3 different types of logit: 1) dynamic logit, 2) autoregressive logit and 3) dynamic autoregressive logit. 
From your previous response, I understood that logitx(y, ar = 1, xreg = x) is the dynamic form. How should I specify the logitx function in order to estimate autoregressive and the dynamic autoregressive?

**Comment by jforest443** [comment]
I'm not looking at the paper but sounds like you want to lag the x variables? 

Sent from Yahoo Mail on Android 
 
  On Sat, Apr 8, 2023 at 5:21 PM, ***@***.***> wrote:   


But I want to keep the regressors. Just like in the original paper, I would like to estimate the 3 different types of logit: 1) dynamic logit, 2) autoregressive logit and 3) dynamic autoregressive logit.
From your previous response, I understood that logitx(y, ar = 1, xreg = x) is the dynamic form. How should I specify the logitx function in order to estimate autoregressive and the dynamic autoregressive?

**Comment by nkretzmann** [comment]
No, my x variables are already lagged. I apologize in advance for not making myself clear.
I'm aiming to replicate the paper in which the logitx function was based on.
In the paper, they have four different forecasting models, 1) static (which is the regular logit), 2) dynamic, 3) autoregressive and 4) dynamic autoregressive (the image below is from the paper).

![Screenshot 2023-04-08 185621](https://user-images.githubusercontent.com/79531090/230744197-299c71c7-9700-4917-8205-6b9063035b69.jpg)

So, my question is: the specification 'model <- logitx(y, ar = 1, xreg = x)' corresponds to which of the forecasting models from the paper? (obviously it won't be the static one). And how should I modify the logitx specifications in order to estimate the others?

**Comment by jforest443** [comment]
Send me a link to the paper.  Ironically, I'm also working on a similar model in Oxmetrics.  My GA is trying to implement in R.

Sent from Yahoo Mail on Android 
 
  On Sat, Apr 8, 2023 at 6:03 PM, ***@***.***> wrote:   


No, my x variables are already lagged. I apologize in advance for not making myself clear.
I'm aiming to replicate the paper in which the logitx function was based on.
In the paper, they have four different forecasting models, 1) static (which is the regular logit), 2) dynamic, 3) autoregressive and 4) dynamic autoregressive (the image below is from the paper).



So, my question is: the specification 'model <- logitx(y, ar = 1, xreg = x)' corresponds to which of the forecasting models from the paper? (obviously it won't be the static one). And how should I modify the logitx specifications in order to estimate the others?

**Comment by jforest443** [comment]
My guess without seeing the paper is dynamic autoregressive because you have both ar and lagged regressors. You are doing an ardl via probit.
Sent from Yahoo Mail on Android 
 
  On Sat, Apr 8, 2023 at 6:06 PM, Jim ***@***.***> wrote:   Send me a link to the paper.  Ironically, I'm also working on a similar model in Oxmetrics.  My GA is trying to implement in R.

Sent from Yahoo Mail on Android 
 
  On Sat, Apr 8, 2023 at 6:03 PM, ***@***.***> wrote:   


No, my x variables are already lagged. I apologize in advance for not making myself clear.
I'm aiming to replicate the paper in which the logitx function was based on.
In the paper, they have four different forecasting models, 1) static (which is the regular logit), 2) dynamic, 3) autoregressive and 4) dynamic autoregressive (the image below is from the paper).



So, my question is: the specification 'model <- logitx(y, ar = 1, xreg = x)' corresponds to which of the forecasting models from the paper? (obviously it won't be the static one). And how should I modify the logitx specifications in order to estimate the others?

**Comment by nkretzmann** [comment]
this is the link for the paper: https://www.jstor.org/stable/40043114


I'm not so sure about it being a dynamic autoregressive, given that in the help section for the logitx function, it says that a lagged y value is not added by default. But even if that is the case, then I would like to know how to remove it in order to also estimate an autoregressive (without the dynamic effects).

**Comment by jforest443** [comment]
The answer to your question is in the documentation only a few lines in. I always recommend the documentation before asking people online on something this basic. 
You just need to specify NULL appropriately. 
logitx: Estimate an autoregressive logit model with covariates in gets: General-to-Specific (GETS) Modelling and Indicator Saturation Methods


| 
| 
|  | 
logitx: Estimate an autoregressive logit model with covariates in gets: ...


 |

 |

 |



---------------------------------------------------------------------------------CONFIDENTIALITY NOTICE: This e-mail and any of its attachments are for the sole use of the intended recipient and it may contain information that is proprietary, privileged, confidential, or otherwise legally exempt from disclosure. If you have received this e-mail in error, please immediately notify the sender by e-mail at the address shown above and delete all copies of this message. If you are not the intended recipient, please be aware that you are not authorized to open, read, print, retain, copy, or disseminate this message or any part of it. Thank you for your compliance. 

    On Saturday, April 8, 2023 at 06:17:50 PM EDT, nkretzmann ***@***.***> wrote:  
 
 


this is the link for the paper: https://www.jstor.org/stable/40043114

I'm not so sure about it being a dynamic autoregressive, given that in the help section for the logitx function, it says that a lagged y value is not added by default. But even if that is the case, then I would like to know how to remove it in order to also estimate an autoregressive (without the dynamic effects).

**Comment by nkretzmann** [comment]
Thank you for your response, but I'm still a bit confused. If you don't mind expanding a little bit of your understanding of the matter, it would be very much appreciated. 
It's still not clear for me which of the specifications correspond to which model from the original paper.
If I set ar = NULL instead of 1, does that mean I'm running an autoregressive model or a dynamic model?

**Comment by jforest443** [comment]
Ar is the lag order for the lagged depend variable y. If you don't estimate any lags of your, it isn't autoregressive. 
If x includes lagged exogeneous regressors then it is dynamic.  If all x are contemporaneous it is a static model.

Sent from Yahoo Mail on Android 
 
  On Sat, Apr 8, 2023 at 7:54 PM, ***@***.***> wrote:   


Thank you for your response, but I'm still a bit confused. If you don't mind expanding a little bit of your understanding of the matter, it would be very much appreciated.
It's still not clear for me which of the specifications correspond to which model from the original paper.
If I set ar = NULL instead of 1, does that mean I'm running an autoregressive model or a dynamic model?

**Comment by nkretzmann** [comment]
I'm sorry, but reading the original paper and other related papers, I don't think that is the case. 
A static model may have lagged exogenous regressors. The dynamic includes lagged y, and autoregressive means including lagged values of previous probabilities.
See the definitions below from https://onlinelibrary.wiley.com/doi/abs/10.1002/for.1161

![image](https://user-images.githubusercontent.com/79531090/230748034-0b6041d9-36d9-45ef-9565-5d9208ac0545.png)

**Comment by jforest443** [comment]
Ok. Go with that. 

Sent from Yahoo Mail on Android 
 
  On Sat, Apr 8, 2023 at 8:25 PM, ***@***.***> wrote:   


I'm sorry, but reading the original paper and other related papers, I don't think that is the case.
A static model may have lagged exogenous regressors. The dynamic includes lagged y, and autoregressive means including lagged values of previous probabilities.
See the definitions below from https://onlinelibrary.wiley.com/doi/abs/10.1002/for.1161

**Comment by jforest443** [comment]
Thanks for pointing that out.
Any idea how to restrict the intercept to 0 in R?

Sent from Yahoo Mail on Android 
 
  On Sat, Apr 8, 2023 at 8:28 PM, Jim ***@***.***> wrote:   Ok. Go with that. 

Sent from Yahoo Mail on Android 
 
  On Sat, Apr 8, 2023 at 8:25 PM, ***@***.***> wrote:   


I'm sorry, but reading the original paper and other related papers, I don't think that is the case.
A static model may have lagged exogenous regressors. The dynamic includes lagged y, and autoregressive means including lagged values of previous probabilities.
See the definitions below from https://onlinelibrary.wiley.com/doi/abs/10.1002/for.1161

**Comment by nkretzmann** [comment]
for the logitx you need to specify intercept = FALSE.

**Comment by jforest443** [comment]
I think that just doesn't estimate the intercept not force it to 0. No?

Sent from Yahoo Mail on Android 
 
  On Sat, Apr 8, 2023 at 8:34 PM, ***@***.***> wrote:   


for the logitx you need to specify intercept = FALSE.

**Comment by nkretzmann** [comment]
Thank you so much for the reply and for the chapter, it was very helpful!
However, I have one last doubt. When I run the following:

model4 <- logitx(y, ar = c(1,2), ewma =list(length(c(6,12))), xreg=x)

(which should be equivalent to the second example in page 59 of the chapter you have linked), I get this warning message:

Warning message:
In logitx(y, ar = c(1, 2), ewma = list(length(c(6, 12))), xreg = x) : 
regressor-matrix singular, so dropping: EqWMA(2)

Which means it doesn't show EqWMA(6) and EqWMA(12) when I print(model4):

Date: Mon Apr 17 20:09:46 2023 
Dependent var.: y 
Method: Maximum Likelihood (logit) 
Variance-Covariance: Ordinary 
No. of observations: 292 
Sample: 3 to 294 

Estimation results:

                 coef   std.error  t-stat   p-value    
intercept -4.6331e+00  6.4745e-01 -7.1560 3.457e-12 ***
ar1        2.5395e+01  1.9045e+04  0.0013    0.4995    
ar2       -1.8561e+01  1.9045e+04 -0.0010    0.4996    
mxreg     -4.0581e-01  9.9917e-02 -4.0615 3.146e-05 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
                        
Log-lik.(n=292) -26.7646


However, in the chapter it seems to work. Do you know what I could be doing wrong?
Thanks again!

**Comment by nkretzmann** [comment]
Thank you so much for the reply and for the chapter, it was very helpful!
However, I have one last doubt. When I run the following:

`model4 <- logitx(y, ar = c(1,2), ewma =list(length(c(6,12))), xreg=x)`

(which should be equivalent to the second example in page 59 of the chapter you have linked), I get this warning message:

`Warning message:
In logitx(y, ar = c(1, 2), ewma = list(length(c(6, 12))), xreg = x) :
regressor-matrix singular, so dropping: EqWMA(2)
`

Which means it doesn't show EqWMA(6) and EqWMA(12) when I print(model4):

![image](https://user-images.githubusercontent.com/79531090/232631527-1670a904-f59f-44b7-9f0a-cf8c1c1ecf26.png)


However, in the chapter it seems to work. Do you know what I could be doing wrong?
Thanks again!

**Comment by gsucarrat** [comment]
It seems you are missing a "=" in the `ewma` argument. Try
writing `list(length=c(6,12))` instead of list(length(c(6,12))). Note that
the argument you put in `ewma` is essentially passed on to the function
`eqwma()`, see `help(eqwma)`.
