### ISSUE TITLE
Suggest to show significance *** as standard

### ISSUE THREAD

**Issue by moritzpschwarz** [gsucarrat/gets#8]
Currently the default when printing `arx`, `gets` and `isat` results is not to display the `***` for significant results. 

For convenience, I would suggest that we set the appropriate part in the `print.isat` etc. functions as `signif.stars = TRUE`.

What do you think?

**Comment by gsucarrat** [comment]
That would indeed be nice. I it's OK with you, I suggest you make the changes necessary in print.gets() and print.isat(), since signif.stars is currently not an argument available in those functions. A couple of years ago, I failed to make printCoefmat() print the estimation results in an appropriate manner. So I just put it aside and left it for later.

**Comment by moritzpschwarz** [comment]
Thanks for that @gsucarrat !
I have now implemented the *** in all outputs and I think I have found a way to also print the stars in the upper part of `print.gets`. It is part of pull request #11 now

Just to illustrate it, I have for now implemented adding the *** in all outputs (including for the diagnostic checks, which I'd argue helps quite nicely to see if the model passes the test) - but please do turn down my changes if you feel that this confuses the eye as there are too many outputs. Very happy also to just have it in arx.

**Comment by moritzpschwarz** [comment]
Still keeping this open even though this was implemented for `arx` and `getsm` but the pull request #11 still requires are review by @fpretis or @jjreade for the `isat` function.

**Comment by moritzpschwarz** [comment]
Implemented!
